name: Samson Deploy
description: Sends webhooks to Samson to run deploys
author: https://github.com/envato
requirements:
  - jq
configuration:
  properties:
    url:
      type: string
  required:
    - url
  additionalProperties: false
