#!/bin/bash
set -euo pipefail

echo "--- Sending Samson webhook"

url=${BUILDKITE_PLUGIN_SAMSON_DEPLOY_URL?}

if [[ "${BUILDKITE_PLUGIN_SAMSON_DEPLOY_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  set -x
fi

headers=( "-H" "HTTP_X_BUILDKITE_EVENT: build.finished" "-H" "Content-Type: application/json")

payload=$(jq -n --arg id "$BUILDKITE_BUILD_ID" \
  --arg url "$BUILDKITE_BUILD_URL" \
  --arg message "$BUILDKITE_MESSAGE" \
  --arg num "$BUILDKITE_BUILD_NUMBER" \
  --arg commit "$BUILDKITE_COMMIT" \
  --arg branch "$BUILDKITE_BRANCH" \
  --arg source "$BUILDKITE_SOURCE" '{
  "event": "build.finished",
  "build": {
    "id": $id,
    "url": "UNIMPLEMENTED",
    "web_url": $url,
    "number": $num | tonumber,
    "state": "passed",
    "blocked": false,
    "message": $message,
    "commit": $commit,
    "branch": $branch,
    "tag": null,
    "source": $source,
    "creator": null,
    "created_at": "1970-01-01 00:00:00 UTC",
    "scheduled_at": "1970-01-01 00:00:00 UTC",
    "started_at": "1970-01-01 00:00:00 UTC",
    "finished_at": "1970-01-01 00:00:00 UTC",
    "meta_data": {},
    "pull_request": null
  },
  "pipeline": {},
  "sender": null
}')

curl --fail \
    --request POST \
    --silent \
    --show-error \
    "${headers[@]}" \
    -d "${payload}" \
    "$url"
